// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $partials_paged_rows from "./routes/partials/paged-rows.tsx";
import * as $load_more_button from "./islands/load-more-button.tsx";
import * as $nav from "./islands/nav.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/partials/paged-rows.tsx": $partials_paged_rows,
  },
  islands: {
    "./islands/load-more-button.tsx": $load_more_button,
    "./islands/nav.tsx": $nav,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
